Repository smartlyio/collect-coverage-action, pull requests merged in 2022-08, with the labels that each got.

#4 add autotagging
  .github/templates/release.yml.erb
  .github/workflows/check_release_label.yml
  .github/workflows/release.generated.yml
  package.json
Labels: patch

#5 lose extra deps from relesae
  .github/templates/release.yml.erb
  .github/workflows/release.generated.yml
Labels: patch

#6 publish item counts
  src/coverage.ts
Labels: minor

#7 Move CI to ubuntu 20.04 from deprecated 18.04 runners
  .github/workflows/check_release_label.yml
Labels: no release
